[package]
name = "delivery_service"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
logistics_platform = "0x8b0988a046fb22800ea370b3194ade0709861ed987cd978c86ed4fc0709ca2ea"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
