[package]
name = "delivery_service"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
logistics_platform = "0xa9d1702ac29b697d1a150e0eb0cfba91fd574404df3d06874ac167468a1c0822"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
